apiVersion: apps/v1
kind: Deployment
metadata:
  name: twotier-frontend
spec:
  selector:
    matchLabels:
      app: twotier-frontend
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: twotier-frontend
        tier: frontend
        track: stable
    spec:
      containers:
        - name: twotier-frontend
          image: myacr001.azurecr.io/k8sfrontend:latest
          ports:
            - name: http
              containerPort: 5107
          env:
          - name: BACKEND_HOST
            value: "app-backend.mydemo.svc.cluster.local"
          - name: BACKEND_PORT
            value: "5106"
      imagePullSecrets:
        - name: mysecret
---
apiVersion: v1
kind: Service
metadata:
  name: app-frontend
spec:
  selector:
    app: twotier-frontend
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 5107
    targetPort: 5107
    nodePort: 32001
  type: NodePort