# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'   # other options: 'macOS-10.13', 'vs2017-win2016'

variables:
  frontendImageName: $(acr_frontend_image)'
  backendImageName: $(acr_backend_image)'

steps:
# TODO: Define password as secret  
- script: docker build -f ./backend/Dockerfile -t $(backendImageName) .
  displayName: 'build backend container'
- script: docker build -f ./frontend/Dockerfile -t $(frontendImageName) .
  displayName: 'build frontend container'
- script: docker login $(acr_server) -u $(acr_user) -p $(acr_password)
  displayName: 'docker login'
- script: docker push $(backendImageName)
  displayName: 'push backend container'
- script: docker push $(frontendImageName)
  displayName: 'push frontend container'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: './k8s'
    artifactName: drop
